name: Run Linter & Formatter

on:
  push:
    branches: [ "main", "epic/**" ]
  pull_request:
    branches: [ "main", "epic/**" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/CODEOWNERS'

jobs:
  eslint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          src/samples/package-lock.json
    - run: npm ci && (cd src/samples && npm ci)
    - run: npm run lint:ci
